name: CI Pipeline  # Name of the workflow

on: [push, pull_request]  # Trigger the workflow on push or pull request

jobs:
  test:  # Define the job
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout code from the repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Set Python version

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Install required dependencies

      - name: Run Tests
        run: pytest  # Run unit tests using pytest
